# Generated by Django 5.0.7 on 2024-07-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_management', '0002_alter_spam_unique_together_spam_spam_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spam',
            name='spam_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
